"""Add platform_fee_cents to payments table

Revision ID: 531f9c0bbceb
Revises: 6b49993713ef
Create Date: 2026-03-18 18:11:48.117145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '531f9c0bbceb'
down_revision: Union[str, None] = '6b49993713ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with server_default to populate existing rows with 0
    op.add_column('payments', sa.Column('platform_fee_cents', sa.Integer(), nullable=False, server_default='0'))
    # Remove server_default after column is created (we want app-level default, not DB-level)
    op.alter_column('payments', 'platform_fee_cents', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'platform_fee_cents')
    # ### end Alembic commands ###
