"""add_unique_constraint_payment_session_ticket

Revision ID: 596f4997e73a
Revises: 531f9c0bbceb
Create Date: 2026-03-18 21:11:16.806548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '596f4997e73a'
down_revision: Union[str, None] = '531f9c0bbceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_payment_session_ticket', 'payments', ['stripe_session_id', 'ticket_type_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_payment_session_ticket', 'payments', type_='unique')
    # ### end Alembic commands ###
