"""Add customer phone to payments

Revision ID: 5daa9938d4f9
Revises: 3ee6c10714d2
Create Date: 2026-03-04 17:22:40.937908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5daa9938d4f9'
down_revision: Union[str, None] = '3ee6c10714d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('customer_phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'customer_phone')
    # ### end Alembic commands ###
