"""remove unique constraint from stripe_payment_intent_id

Revision ID: 6b49993713ef
Revises: 80d7fa33db67
Create Date: 2026-03-11 16:26:49.009894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b49993713ef'
down_revision: Union[str, None] = '80d7fa33db67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_stripe_payment_intent_id', table_name='payments')
    op.create_index(op.f('ix_payments_stripe_payment_intent_id'), 'payments', ['stripe_payment_intent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_stripe_payment_intent_id'), table_name='payments')
    op.create_index('ix_payments_stripe_payment_intent_id', 'payments', ['stripe_payment_intent_id'], unique=True)
    # ### end Alembic commands ###
