"""Add stripe_account_id to clients

Revision ID: 7c06ed4c4261
Revises: 2363cbc556a9
Create Date: 2026-03-04 16:36:22.621371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c06ed4c4261'
down_revision: Union[str, None] = '2363cbc556a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('stripe_account_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'stripe_account_id')
    # ### end Alembic commands ###
