"""allow multiple tickets per session

Revision ID: 80d7fa33db67
Revises: 5daa9938d4f9
Create Date: 2026-03-04 17:45:32.235581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80d7fa33db67'
down_revision: Union[str, None] = '5daa9938d4f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_stripe_session_id', table_name='payments')
    op.create_index(op.f('ix_payments_stripe_session_id'), 'payments', ['stripe_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_stripe_session_id'), table_name='payments')
    op.create_index('ix_payments_stripe_session_id', 'payments', ['stripe_session_id'], unique=True)
    # ### end Alembic commands ###
